inherit_from:
  - "https://www.goodcop.style/base.yml"
  - "https://www.goodcop.style/tabs.yml"

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - "lib/phlex-rails.rb"
    - "lib/generators/**/templates/**/*"
  SuggestExtensions: false
