inherit_from:
  - "https://www.goodcop.style/rubocop.yml"
  - "https://www.goodcop.style/tabs.yml"

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - "lib/phlex-rails.rb"

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false


Security/Eval:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false
